# Generated by Django 4.0.8 on 2023-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20220222_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter your represententing gaming_genre  (e.g. Masc,Fem , NoBin, Other)', max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter preferenced language (e.g. English, French, Japanese etc.)', max_length=200),
        ),
    ]
