# Generated by Django 4.0.8 on 2023-03-16 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player2', to=settings.AUTH_USER_MODEL)),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player3', to=settings.AUTH_USER_MODEL)),
                ('player4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player4', to=settings.AUTH_USER_MODEL)),
                ('player5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player5', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('completed', 'completed')], default='open', max_length=20)),
                ('teams', models.ManyToManyField(to='users.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_winner', to='users.team')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_online', models.BooleanField(blank=True, default=False)),
                ('looking_for_group', models.BooleanField(blank=True, default=False)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('valorantName', models.TextField(blank=True, max_length=20)),
                ('valorantTagline', models.TextField(blank=True, max_length=7)),
                ('valorantRegion', models.TextField(blank=True, choices=[('NA', 'NA'), ('EU', 'EU'), ('AP', 'AP'), ('KR', 'KR')])),
                ('valorantLeague', models.TextField(blank=True, max_length=40)),
                ('valorantRangue', models.TextField(blank=True, max_length=40)),
                ('valorantCurrentRR', models.TextField(blank=True, max_length=40)),
                ('valorantCalculatedElo', models.TextField(blank=True, max_length=40)),
                ('valorantKills', models.TextField(blank=True, max_length=40)),
                ('valorantDeaths', models.TextField(blank=True, max_length=40)),
                ('valorantAssists', models.TextField(blank=True, max_length=40)),
                ('valorantBodyshots', models.TextField(blank=True, max_length=40)),
                ('valorantHeadshots', models.TextField(blank=True, max_length=40)),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('O', 'Octavos de final'), ('Q', 'Cuartos de final'), ('SF', 'Semifinales'), ('F', 'Final')], default='O', max_length=2)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='users.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='users.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='users.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='users.team')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
