# Generated by Django 4.0.8 on 2023-02-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_valorantname_profile_valoranttagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='valorantRegion',
            field=models.TextField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='valorantTagline',
            field=models.TextField(blank=True, max_length=4),
        ),
    ]
