# Generated by Django 4.0.8 on 2023-02-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_valorantregion_alter_profile_valoranttagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='valorantCalculatedElo',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='valorantCurrentRR',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='valorantLeague',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='valorantRangue',
            field=models.TextField(blank=True, max_length=40),
        ),
    ]
