# Generated by Django 4.0.8 on 2023-02-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_valorantcalculatedelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valorantRegion',
            field=models.TextField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='valorantTagline',
            field=models.TextField(blank=True, max_length=3),
        ),
    ]
