# Generated by Django 4.0.8 on 2023-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_friendrequest_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valorantTagline',
            field=models.TextField(blank=True, max_length=7),
        ),
    ]
