# Generated by Django 4.0.8 on 2023-03-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
