# Generated by Django 4.0.8 on 2023-03-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='looking_for_group',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
